# Generated by Django 5.1.6 on 2025-03-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0002_remove_cake_price_cart_cartitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='cake',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='cakes.topping'),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='cakes.topping'),
        ),
    ]
