# Generated by Django 5.1.6 on 2025-03-06 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0004_alter_topping_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitems',
            unique_together=set(),
        ),
    ]
