# Generated by Django 5.1.6 on 2025-03-26 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0009_cakesponge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cakesponge',
            name='cake',
        ),
        migrations.AddField(
            model_name='cake',
            name='sponge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponges', to='cakes.cakesponge'),
        ),
    ]
