# Generated by Django 5.1.6 on 2025-03-27 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0011_cake_user_alter_cake_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CakeExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('filling', 'Filling'), ('candle', 'Candle'), ('color', 'Color'), ('decoration', 'Edible Decoration'), ('packaging', 'Packaging')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_modifications', to='cakes.cake')),
                ('candles', models.ManyToManyField(blank=True, related_name='custom_candles', to='cakes.cakeextra')),
                ('colors', models.ManyToManyField(blank=True, related_name='custom_colors', to='cakes.cakeextra')),
                ('decorations', models.ManyToManyField(blank=True, related_name='custom_decorations', to='cakes.cakeextra')),
                ('fillings', models.ManyToManyField(blank=True, related_name='custom_fillings', to='cakes.cakeextra')),
                ('packaging', models.ManyToManyField(blank=True, related_name='custom_packaging', to='cakes.cakeextra')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_cake_modifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cartitems',
            name='custom_modification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cakes.custommodification'),
        ),
    ]
