# Generated by Django 5.1.6 on 2025-03-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0012_cakeextra_custommodification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custommodification',
            name='candles',
        ),
        migrations.RemoveField(
            model_name='custommodification',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='custommodification',
            name='decorations',
        ),
        migrations.RemoveField(
            model_name='custommodification',
            name='fillings',
        ),
        migrations.RemoveField(
            model_name='custommodification',
            name='packaging',
        ),
        migrations.AddField(
            model_name='custommodification',
            name='extras',
            field=models.ManyToManyField(blank=True, to='cakes.cakeextra'),
        ),
    ]
