# Generated by Django 5.1.6 on 2025-03-27 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0013_remove_custommodification_candles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='sponge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponges', to='cakes.cakesponge'),
        ),
        migrations.AlterField(
            model_name='cakesize',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='cakesponge',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
