# Generated by Django 5.1.6 on 2025-03-11 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_alter_address_user'),
        ('cakes', '0007_rename_is_paid_cart_is_ordered_order_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('assigned_orders', models.ManyToManyField(blank=True, related_name='assigned_delivery', to='cakes.order')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
