# Generated by Django 5.1.6 on 2025-03-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_deliveryperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('delivery_person', 'Delivery Person')], default='user', max_length=255),
        ),
    ]
